a=y  y   aa    n nn     j    i    aa
b= y    a  a   n  n   j j    i   a  a
c=y      aa a  n  n    jj    i    aa a
import os,time
print(a)
print(b)
print(c)

time.sleep(0.1)
i=os.system('cls')
print(' ',a)
print(' ',b)
print(' ',c)

time.sleep(0.1)
i=os.system('cls')
print('  ',a)
print('  ',b)
print('  ',c)

time.sleep(0.1)
i=os.system('cls')
print('   ',a)
print('   ',b)
print('   ',c)

time.sleep(0.1)
i=os.system('cls')
print('    ',a)
print('    ',b)
print('    ',c)

time.sleep(0.1)
i=os.system('cls')
print('     ',a)
print('     ',b)
print('     ',c)

time.sleep(0.1)
i=os.system('cls')
print('      ',a)
print('      ',b)
print('      ',c)

time.sleep(0.1)
i=os.system('cls')
print('       ',a)
print('       ',b)
print('       ',c)

time.sleep(0.1)
i=os.system('cls')
print('        ',a)
print('        ',b)
print('        ',c)

time.sleep(0.1)
i=os.system('cls')
print('         ',a)
print('         ',b)
print('         ',c)

time.sleep(0.1)
i=os.system('cls')
print('          ',a)
print('          ',b)
print('          ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ',a)
print('           ',b)
print('           ',c)

time.sleep(0.1)
i=os.system('cls')
print('            ',a)
print('            ',b)
print('            ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('            ',a)
print('            ',b)
print('            ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ',a)
print('           ',b)
print('           ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('          ',a)
print('          ',b)
print('          ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('         ',a)
print('         ',b)
print('         ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('        ',a)
print('        ',b)
print('        ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('       ',a)
print('       ',b)
print('       ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('      ',a)
print('      ',b)
print('      ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('     ',a)
print('     ',b)
print('     ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('           ')
print('    ',a)
print('    ',b)
print('    ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('           ')
print('   ',a)
print('   ',b)
print('   ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print('           ')
print('  ',a)
print('  ',b)
print('  ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('           ')
print(' ',a)
print(' ',b)
print(' ',c)

time.sleep(0.1)
i=os.system('cls')
print('           ')
print('',a)
print('',b)
print('',c)

time.sleep(0.1)
i=os.system('cls')
print(a)
print(b)
print(c)