print "y     y     a      n nnnn           jj   iiiiii       a"
print " y   y     a a     nn   n           jj     ii        a a"
print "  y y     a   a    n    n           jj     ii       a   a"
print "   y     aaaaaaa   n    n           jj     ii      aaaaaaa"
print "  y     a       a  n    n        j  jj     ii     a       a"
print " y     a         a n    n         jjj    iiiiii  a         a"    
